# Generated by Django 3.2.16 on 2022-10-23 09:53

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graf', '0002_test_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='backgroundColor',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='test',
            name='borderColor',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
