# Generated by Django 3.2.16 on 2022-10-24 15:17

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graf', '0003_auto_20221023_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='backgroundColor',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='test',
            name='borderColor',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
    ]
