# Generated by Django 3.2.16 on 2022-10-25 16:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graf', '0004_auto_20221024_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='backgroundColor',
        ),
        migrations.AlterField(
            model_name='test',
            name='borderColor',
            field=colorfield.fields.ColorField(default='#FF00FF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='test',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
    ]
